### PR TITLE
Crates maintenance and version bump

### PR DESCRIPTION
**Pull request by CBenoit**
cc @RRRadicalEdward

### CODE REVIEW

**Review by RRRadicalEdward — APPROVED** [review]
Now picky is more awesome with fixing all upper case acronyms warnings 😀

**Comment by CBenoit** [comment]
> Now picky is more awesome with fixing all upper case acronyms warnings grinning

Thank you! :smile: 
Also, can you approve the changes? I need at least one approval in order to merge :slightly_smiling_face:

**Review by RRRadicalEdward — APPROVED** [review]

**Comment by RRRadicalEdward** [comment]
> > Now picky is more awesome with fixing all upper case acronyms warnings grinning
> 
> Thank you! smile
> Also, can you approve the changes? I need at least one approval in order to merge slightly_smiling_face

Sure!

**Comment by CBenoit** [comment]
Perfect, thank you!

**Pull request merged**
