### PR TITLE
chore(deps): update Cargo.lock

### PR DESCRIPTION
**Pull request by MathieuMorrissette**
Update cargo lock file to dismiss some dependabot alerts.

### CODE REVIEW

**Comment by CBenoit** [comment]
Thank you!
However, this is breaking the CI. Could you try to target only the dependencies using `cargo update -p` and see if it’s enough?
Otherwise, we’ll have to update our MSRV requirements.

**Review by CBenoit — COMMENTED** [review]
Thank you!
However, this is breaking the CI. Could you try to target only the dependencies using `cargo update -p` and see if it’s enough?
Otherwise, we’ll have to update our MSRV requirements.

**Comment by MathieuMorrissette** [comment]
@CBenoit  done!

**Review by CBenoit — APPROVED** [review]
Nice! Thank you! 🙏

**Pull request merged**
