### PR TITLE
Fetch curve info from private_key_algorithm

### PR DESCRIPTION
**Pull request by dpogorzelski**
This fixes the issue described here: https://github.com/Devolutions/picky-rs/issues/100#issuecomment-1118363996

### CODE REVIEW

**Comment by CBenoit** [comment]
Thank you! I’ll review this on Monday :slightly_smiling_face:

**Comment by dpogorzelski** [comment]
perhaps checking key type first is better ( `private_key_info::PrivateKeyValue::RSA(_)` )so that a meaningful error is returned when the key is RSA

**Comment by CBenoit** [comment]
> perhaps checking key type first is better ( `private_key_info::PrivateKeyValue::RSA(_)` )so that a meaningful error is returned when the key is RSA

Yeah, I think it would be better with the check. Looks good to me otherwise!

**Review by CBenoit — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
